### ISSUE TITLE
Documentation does not include (in)compatibility with old work item process template technology

### ISSUE THREAD

**Issue by RudiMT** [Sedeniono/ADO-History-Diff#1]
Current behavior:
As an admin, I'm installing the extension on AzureDevOps 2020 with a "old" work item process template, and see that the extension does not create the tab as advertised, assuming it would work as nothing is stated about this compatibility trap. We are deriving from "msf formal".

Expected behavior:
A note if the "old" work item process templates (witadmin.exe) can be supported with a template modification similar to MSDevLabs) vsts-extensions-multivalue-control would be helpful.

**Comment by Sedeniono** [comment]
I guess you are talking about the [XML process model](https://learn.microsoft.com/en-us/azure/devops/organizations/settings/work/hosted-xml-process-model?view=azure-devops)? To be honest, I was not aware of this process model. Thanks for pointing this out! 

In principle, I don't see why my extension shouldn't work with the XML process model. According to [this link](https://learn.microsoft.com/en-us/previous-versions/azure/devops/reference/xml/weblayout-xml-elements?view=tfs-2017&preserve=true#form-extensions) (and the [documentation of the multivalue-control](https://github.com/microsoft/vsts-extension-multivalue-control/blob/master/xmldetails.md)) I **guess** you need to add
```XML
 <Extensions>
     <Extension Id="Sedenion.HistoryDiff" />
 </Extensions>
```
to the WIT definition (prior to the `Page` element)? But I haven't tried it yet. I will see if I can figure out how to setup ADO with the XML process model in the next few days to try it out.

**Comment by Sedeniono** [comment]
@RudiMT OK, I tried it out and updated the readme with detailed installation instructions on how to [upload](https://github.com/Sedeniono/ADO-History-Diff?tab=readme-ov-file#uploading-the-extension-to-azure-devops-server) the vsix package and then on how to [edit the XML via the `witadmin` tool](https://github.com/Sedeniono/ADO-History-Diff?tab=readme-ov-file#installation-for-the-on-premises-xml-process-model).
Please let me know if this is not working for you. Till then, I am closing this issue as "Completed".

**Comment by RudiMT** [comment]
@Sedeniono Thanks for the very quick response and the accurate instructions. We are using this extension now, main purpose is requirements and similar, where it makes life a lot easier. Haven't seen any side effects so far.
